openapi: 3.0.1
info:
  title: Animal API

paths:
  /dogs:
    requestBody:
      example: [
        { "dog": 1}
      ]

  /cats:
    requestBody:
      example: [
        { "cat": 2 },
        { "cat": 3 }
      ]
