openapi: 3.1.0
info:
  title: AnimalAPI
  version: 1.0.0

paths:
  /dogs:
    get:
      content:
        requestBody:
          example: [
            { "dog": 1}
          ]

  /cats:
    get:
      content:
        requestBody:
          example: [
            { "cat": 2 },
            { "cat": 3 }
          ]
